import { defaultSchema } from "rehype-sanitize";

/**
 * Sanitization schema for proposal descriptions (untrusted blockchain input).
 * Allowlist of safe HTML elements to prevent XSS attacks.
 */
export const proposalSanitizeSchema = {
  ...defaultSchema,
  tagNames: [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "br",
    "hr",
    "div",
    "span",
    "ul",
    "ol",
    "li",
    "blockquote",
    "pre",
    "code",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "s",
    "del",
    "ins",
    "sup",
    "sub",
    "a",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "dl",
    "dt",
    "dd",
    "details",
    "summary",
  ],
  attributes: {
    a: ["href", "title", "rel", "target"],
    th: ["align", "valign", "scope"],
    td: ["align", "valign"],
    code: ["className"],
    pre: ["className"],
    "*": ["id"],
  },
  protocols: {
    href: ["http", "https", "mailto"],
  },
  strip: ["script", "style"],
};
